### ISSUE TITLE
Remove the need to run this Docker container in privileged mode

### ISSUE THREAD

**Issue by tigerblue77** [linuxserver/docker-kasm#22]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Remove the need to run this Docker container in privileged mode

### Reason for change

Running privileged containers is a bad practice and cannot be done in Docker Swarm mode.

### Proposed code change

This docker compose file is almost working :
```yaml
version: "3.7"

services:
  application:
    # container_name: {{ Kasm_Docker_stack_name }}
    image: lscr.io/linuxserver/kasm
    deploy:
      restart_policy:
        condition: on-failure
    # privileged: true
    environment:
      KASM_PORT: "{{ Kasm_container_port_to_expose }}"
      TZ: "Europe/Paris"
    volumes:
      - "/sys/kernel/security:/sys/kernel/security:ro"
      - "/usr/sbin/modprobe:/usr/sbin/modprobe:ro"
      - "/usr/lib:/usr/lib:ro"
      - "/lib:/lib:ro"
      - "/tmp:/tmp:rw"
      - "{{ Kasm_cgroups_Docker_volume_name }}:/sys/fs/cgroup:rw"
      - "{{ Kasm_data_Docker_volume_name }}:/opt:rw"
      - "{{ Kasm_profiles_Docker_volume_name }}:/profiles:rw" # optional
      # - "/dev/input:/dev/input" # optional
      # - "/run/udev/data:/run/udev/data" # optional
    ports:
      - "{{ Kasm_container_setup_port_to_expose }}:3000/TCP"
      - "{{ Kasm_container_port_to_expose }}:{{ Kasm_container_port_to_expose }}/TCP"

volumes:
  {{ Kasm_data_Docker_volume_name }}:
  {{ Kasm_profiles_Docker_volume_name }}:
  {{ Kasm_cgroups_Docker_volume_name }}:
```
But gives me the following errors :
> /bin/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /bin/sh)

> /bin/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/sh)

Ran the following command in my Docker host to find this "GLIBC" library :
```bash
find / -name "*GLIBC*" -not -path "/mnt/*"
```
but found nothing.
