### ISSUE TITLE
[BUG] 'Lossless' Unavailable through Reverse Proxy

### ISSUE THREAD

**Issue by zimmra** [linuxserver/docker-kasm#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Under `Streaming Quality` I am able to enable lossless when accessing the workspace
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/4d60d116-fbb7-4605-9a92-5c86256c5f77)

But when trying to access through reverse proxy (nginx proxy manager, in my case) I am unable to access the option
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/efba2103-fcdc-4e08-8b34-0966cfc2c551)

I have tried this with the container set to bridge networking, as well as host networking, on my server and the result is the same

### Steps To Reproduce

1. Install linuxserver/docker-kasm, and finish setup process
2. Setup reverse proxy configuration on host machine
	- Be sure to include the following in the config, per Kasm:
	  -  ```conf
  	        add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
            add_header 'Cross-Origin-Opener-Policy' 'same-origin';
            add_header 'Cross-Origin-Resource-Policy' 'same-site'; 
         ```
3. Set Proxy Port to 0 in Admin>Infrastructure>Zones>Proxy Connections
4. Access container via Reverse Proxy URL
5. Attempt to set container Streaming Quality to Lossless 

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: directly from Docker (not from apt)
```

### CPU architecture

x86-64

### Docker creation

```yaml
---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    network_mode: host
    privileged: true
    environment:
      - KASM_PORT=4435
      - DOCKER_MTU=1500 #optional
    volumes:
      - /dockercfg/kasm/config:/opt
      - /dockercfg/kasm/profiles:/profiles #optional
      - /dockercfg/kasm/volumes:/volumes
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3065:3000 # vestigial from bridge mode
      - 4435:4435 # vestigial from bridge mode
    restart: unless-stopped
```

### Container logs

Logs do not indicate streaming mode, and do not indicate any errors

**Comment by aptalca** [comment]
Iirc lossless requires the use of the internal 3001 (https) port

**Comment by zimmra** [comment]
> Iirc lossless requires the use of the internal 3001 (https) port

I will give it a try later, but if that's the case then why does it work when going direct to the IP (which is where my first screenshot came from) which is https://192.168.2.2:4435

**Comment by zimmra** [comment]
@aptalca had an opportunity to test sooner than I though

Entirely new Kasm setup, with KASM_PORT set to 3001 and the option still isn't present when accessing through the reverse proxy

```yaml
---
version: "2.1"
services:
  kasm2:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm2
    privileged: true
    environment:
      - KASM_PORT=3001
    volumes:
      - /dockercfg/kasm2/config:/opt
      - /dockercfg/kasm2/profiles:/profiles #optional
      - /dockercfg/kasm2/volumes:/volumes
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3066:3000
      - 3001:3001
    restart: unless-stopped
```
## Direct to IP (https://192.168.2.2:3001)
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/0d99eafb-6fc5-4fe6-ac10-ac9c7a48ce01)


## Through Reverse Proxy
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/92a02e45-3666-4d8b-980e-6d789b0281c0)


## NPM Custom Config
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/d821c948-ebbe-4b66-aff9-58a762cb2ddb)

**Comment by aptalca** [comment]
What address are you putting in the browser to access?

**Comment by zimmra** [comment]
> What address are you putting in the browser to access?

It works going direct to my docker host, https://192.168.2.2:4435 (as well as https://192.168.2.2:3001 on this second 'test' setup I spun up)

It does not work going through my reverse proxy, https://kasm.[MYFQDN].io

**Comment by aptalca** [comment]
As detailed in the readme, the outside port needs to match the internal port

Either you set the internal port to `443` and access at `https://kasm.[myfqdn].io` or you set it to `4435` and access it at `https://kasm.[myfqdn].io:4435`

**Comment by zimmra** [comment]
> As detailed in the readme, the outside port needs to match the internal port

My setup followed the readme instructions exactly.... 

>Unlike other containers the web interface port (default 443) needs to be set for the env variable KASM_PORT and both the inside and outside port IE for 4443 KASM_PORT=4443 -p 4443:4443

my KASM_PORT, externally mapped port, and container internal port were all set to be the same (normally I would leave the interal port as default and remap to a different one on the host) - it doesn't mention that the reverse proxy port _also_ needs to match this

So with your current suggestion, setup now I setup an additional IP address so that now I have KASM_PORT set to 443, as well as the ports mapped to 443:443 and still the same result.

#### Docker Compose
```yaml
---
version: "2.1"
services:
  kasm2:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm2
    privileged: true
    environment:
      - KASM_PORT=443
      - DOCKER_MTU=1500 #optional
    volumes:
      - /dockercfg/kasm2/config:/opt
      - /dockercfg/kasm2/profiles:/profiles #optional
      - /dockercfg/kasm2/volumes:/volumes
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - "192.168.2.16:3066:3000"
      - "192.168.2.16:443:443"
    restart: unless-stopped
```

### Connecting to IP (https://192.168.2.16)
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/9fca54e4-db5b-498e-888d-0272e1f2beca)
#### Logs inside container within kasm when this is accessed via https://192.168.2.16:443

- [ip-connection-logs.txt](https://github.com/linuxserver/docker-kasm/files/12491748/ip-connection-logs.txt)
- Reading these looks like its failing, but from the browser everything works as intended and you wouldn't know the logs are going 'crazy' like this


### Connecting through reverse proxy
![image](https://github.com/linuxserver/docker-kasm/assets/28514085/e789ebd0-a385-465e-abf3-5884382acf64)
#### Logs inside container within kasm when this is accessed via https://192.168.2.16:443
- [reverse-proxy-connection-logs.txt](https://github.com/linuxserver/docker-kasm/files/12491773/reverse-proxy-connection-logs.txt)
	- 10.10.10.2 is the remote machine I am accessing on in a web browser, and 172.20.0.1 is the docker network subdomain my reverse proxy lives on (IP is 172.20.0.5)
