### ISSUE TITLE
unable to apply caps (LXC, userns-remap)

### ISSUE THREAD

**Issue by jyio** [linuxserver/docker-kasm#4]
Thank you for your hard work. I've been running Kasm Workspaces in a separate LXC container and that seemed somewhat awkward. I look forward to running Kasm itself on Docker. I seem to have hit a little snag.

My current setup has Docker running with userns-remap inside an LXC container. I modified the recommended docker-compose file to mount some volumes and make it run as root:

```yaml
---
version: "2.1"
services:
  main:
    image: lscr.io/linuxserver/kasm:latest
    userns_mode: host
    privileged: true
    security_opt:
      - apparmor:unconfined
    environment:
      - KASM_PORT=443
      - TZ=America/New_York
      - DOCKER_HUB_USERNAME=USER #optional
      - DOCKER_HUB_PASSWORD=PASS #optional
    ports:
      - 3000:3000
      - 443:443
    volumes:
      - data:/opt
      - profiles:/profiles #optional
    restart: unless-stopped
volumes:
  data:
  profiles:
```

... and kicked it off with `docker-compose up -d`

## Expected Behavior

Container starts.

## Current Behavior

```
Creating kasm_main_1 ... error

ERROR: for kasm_main_1  Cannot start service main: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply caps: operation not permitted: unknown

ERROR: for main  Cannot start service main: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply caps: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
```

Does Kasm want additional capabilities to be added using `cap_add`?

## Steps to Reproduce
1. Have Docker with userns-remap inside LXC.
2. Create above `docker-compose.yml` file.
3. Run `docker-compose up -d`.
4. 💥

## Environment
**OS:** Debian 11.4 on host, Debian 12 (testing) in container.
**CPU architecture:** x86_64
**How docker service was installed:** Using [recommended process](https://docs.docker.com/engine/install/debian/).

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -d`

## Docker logs
Empty...
