### ISSUE TITLE
[BUG] Could not mount /sys/kernel/security

### ISSUE THREAD

**Issue by TheZoker** [linuxserver/docker-kasm#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to install the latest version of kasm, I get the following error:
```
mount: /sys/kernel/security: permission denied.
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
time="2023-10-12T01:29:49.749588880+02:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```

### Steps To Reproduce

1. Create docker-compose file:
```
version: '3.8'
services:
  kasm:
    image: lscr.io/linuxserver/kasm
    container_name: Kasm
    restart: always
    privileged: true
    ports:
      - 443:443
      - 3000:3000
    volumes:
      - ~/files/kasm/data:/opt
      - ~/files/kasm/profiles:/profiles
    environment:
      - TZ=Europe/Berlin
      - KASM_PORT=443
      - PUID=1000
      - PGID=1000
```

### Environment

```markdown
- OS: alpine OS as LXC
- How docker service was installed: `apk install docker docker-compose`
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose up
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
mount: /sys/kernel/security: permission denied.
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
time="2023-10-12T01:29:49.749588880+02:00" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```
