### ISSUE TITLE
[BUG] mount: /sys/kernel/security: permission denied

### ISSUE THREAD

**Issue by Piero24** [linuxserver/docker-kasm#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to install the latest version of kasm on casaOS, I get the following error:
```
Kasm  | [custom-init] No custom files found, skipping...
Kasm  | [ls.io-init] done.
Kasm  | /usr/local/bin/dockerd-entrypoint.sh: 150: modprobe: not found
Kasm  | mount: /sys/kernel/security: permission denied.
Kasm  | Could not mount /sys/kernel/security.
Kasm  | AppArmor detection and --privileged mode might break.
Kasm  | mount: /tmp: permission denied.
```

### Steps To Reproduce

Install it from the CasaOS appstore.

The Kasm.yalm file is:

```
name: linuxserver-kasm
services:
  app:
    cpu_shares: 90
    command: []
    container_name: Kasm
    deploy:
      resources:
        limits:
          memory: 15775M
    environment:
      - DOCKER_HUB_PASSWORD=
      - DOCKER_HUB_USERNAME=
      - DOCKER_MTU=1500
      - KASM_PORT=443
    image: linuxserver/kasm:1.14.0
    labels:
      icon: https://kasm-ci.s3.amazonaws.com/kasm_wide.png
    ports:
      - target: 3000
        published: "3332"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/kasm/opt
        target: /opt
      - type: bind
        source: /DATA/AppData/kasm/profiles
        target: /profiles
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
    x-casaos:
      envs:
        - container: KASM_PORT
          description:
            en_us: Specify the port you bind to the outside for Kasm Workspaces.
        - container: DOCKER_HUB_USERNAME
          description:
            en_us: Optionally specify a DockerHub Username to pull private images.
        - container: DOCKER_HUB_PASSWORD
          description:
            en_us: Optionally specify a DockerHub password to pull private images.
        - container: DOCKER_MTU
          description:
            en_us: Optionally specify the mtu options passed to dockerd.
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
networks:
  default:
    name: linuxserver-kasm_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: WisdomSky
  category: LinuxServer.io
  description:
    en_us: Kasm Workspaces is ...
  developer: LinuxServer.io
  hostname: ""
  icon: https://kasm-ci.s3.amazonaws.com/kasm_wide.png
  index: /
  main: app
  port_map: "3332"
  scheme: http
  store_app_id: linuxserver-kasm
  tagline:
    en_us: Workspaces is ...
  thumbnail: https://kasm-ci.s3.amazonaws.com/kasm_wide.png
  title:
    custom: ""
    en_us: Kasm

```

### Environment

```markdown
- OS: Ubuntu 22.04 LTS 
- How docker service was installed: From the casaOS appstore
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose
```

### Container logs

```bash
Kasm  | [migrations] started
Kasm  | [migrations] no migrations found
Kasm  | usermod: no changes
Kasm  | ───────────────────────────────────────
Kasm  | 
Kasm  | 
Kasm  |       ██╗     ███████╗██╗ ██████╗ 
Kasm  |       ██║     ██╔════╝██║██╔═══██╗
Kasm  |       ██║     ███████╗██║██║   ██║
Kasm  |       ██║     ╚════██║██║██║   ██║
Kasm  |       ███████╗███████║██║╚██████╔╝
Kasm  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
Kasm  | 
Kasm  | 
Kasm  |    Brought to you by linuxserver.io
Kasm  | ───────────────────────────────────────
Kasm  | 
Kasm  | 
Kasm  | To support LSIO projects visit:
Kasm  | https://www.linuxserver.io/donate/
Kasm  | 
Kasm  | 
Kasm  | ───────────────────────────────────────
Kasm  | GID/UID
Kasm  | ───────────────────────────────────────
Kasm  | 
Kasm  | 
Kasm  | User UID:    911
Kasm  | User GID:    911
Kasm  | ───────────────────────────────────────
Kasm  | 
Kasm  | 
Kasm  | [custom-init] No custom files found, skipping...
Kasm  | [ls.io-init] done.
Kasm  | /usr/local/bin/dockerd-entrypoint.sh: 150: modprobe: not found
Kasm  | mount: /sys/kernel/security: permission denied.
Kasm  | Could not mount /sys/kernel/security.
Kasm  | AppArmor detection and --privileged mode might break.
Kasm  | mount: /tmp: permission denied.
Kasm  | /usr/local/bin/dockerd-entrypoint.sh: 150: modprobe: not found
Kasm  | mount: /sys/kernel/security: permission denied.
Kasm  | Could not mount /sys/kernel/security.
Kasm  | AppArmor detection and --privileged mode might break.
Kasm  | mount: /tmp: permission denied.
```
