### ISSUE TITLE
[BUG] Unable to lauch when mounted volumes are on a ZFS pool mounted over NFS

### ISSUE THREAD

**Issue by jonny190** [linuxserver/docker-kasm#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dmesg output from insode the continer
```
[1417769.078106] overlayfs: upper fs does not support tmpfile.
[1417769.102210] overlayfs: upper fs does not support RENAME_WHITEOUT.
[1417769.102218] overlayfs: failed to set xattr on upper
[1417769.102220] overlayfs: ...falling back to xino=off.
[1417769.102222] overlayfs: upper fs missing required features.

```

### Expected Behavior

Unknown

### Steps To Reproduce

```
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - KASM_PORT=443
      - DOCKER_MTU=1500 #optional
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/nfs/appdata/kasm/data:/opt
      - /mnt/nfs/appdata/kasm/profiles:/profiles #optional
    restart: unless-stopped
    runtime: nvidia

```

Where fstab has the mount configured 
172.*.5.208:/mnt/local/appdata /mnt/nfs/appdata nfs4   _netdev,auto 0 0

### Environment

```markdown
- OS: Ubuntu 22.04.3
- How docker service was installed: Installed via the guide on the docker website
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
kasm  | [migrations] started
kasm  | [migrations] no migrations found
kasm  | ───────────────────────────────────────
kasm  |
kasm  |       ██╗     ███████╗██╗ ██████╗
kasm  |       ██║     ██╔════╝██║██╔═══██╗
kasm  |       ██║     ███████╗██║██║   ██║
kasm  |       ██║     ╚════██║██║██║   ██║
kasm  |       ███████╗███████║██║╚██████╔╝
kasm  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
kasm  |
kasm  |    Brought to you by linuxserver.io
kasm  | ───────────────────────────────────────
kasm  |
kasm  | To support LSIO projects visit:
kasm  | https://www.linuxserver.io/donate/
kasm  |
kasm  | ───────────────────────────────────────
kasm  | GID/UID
kasm  | ───────────────────────────────────────
kasm  |
kasm  | User UID:    1000
kasm  | User GID:    1000
kasm  | ───────────────────────────────────────
kasm  |
kasm  | [custom-init] No custom files found, skipping...
kasm  | [ls.io-init] done.
kasm  | time="2024-04-17T22:47:11.153763425Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
```
