### ISSUE TITLE
Unable to access the webui

### ISSUE THREAD

**Issue by sendev1** [linuxserver/docker-kasm#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used the docker compose as below in my raspberry pi which runs Debian GNU/Linux 12 (bookworm)

```
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optional
    environment:
      - KASM_PORT=4443
      #- DOCKER_HUB_USERNAME=user #optional
      #- DOCKER_HUB_PASSWORD=pass #optional
      #- DOCKER_MTU=1500 #optional
    volumes:
      - ./data:/opt
      - ./profiles:/profiles #optional
      - ./dev/input:/dev/input #optional
      - ./run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 4443:443
    restart: unless-stopped
````

The container is up
````
docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS
   PORTS                                                                                            NAMES
a326b350ca30   lscr.io/linuxserver/kasm:latest           "/init"                  18 minutes ago   Up 18 minutes           0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:4443->443/tcp, [::]:4443->443/tcp             kasm
````
But when i hit the url `https://my-ip:4443/` i am not seeing any ui. I am seeing `ERR_CONNECTION_REFUSED` in browser.

### Steps To Reproduce

See above.

### Environment

```markdown
- OS:Debian
- How docker service was installed: using Open Media Vault. I other containers running successfully.
```

### CPU architecture

arm64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
Logs

docker logs kasm
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

...+......+...+....+............+...............+...+............+.....+...+......+.......+..+..................+....+.....+......+.........+.+..+.......+...+.....+.+.........+.....+.+..+...+....+..+.........+.......+..+......+.......+............+...+...+..+..........+..+.+..+.......+.....+.+.........+.....+......+.+.....+...+............+.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.......+............+.....+....+.....+.+...+..+......+.......+..+.........+....+...+..+.+......+........+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.................+.+...+............+..+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+...+...+...+.+.........+..+..........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+.............+...+............+..+.+..................+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
```
